/* ============================================================
   Valle Auto Sales — Inventory data
   ------------------------------------------------------------
   The inventory renders from js/inventory.json, which is
   generated by scripts/sync-inventory.mjs from the family's
   Airtable base "Inventario Valle Auto Sales" (app9Rj2rqXxh1QSTy).
   A GitHub Action (.github/workflows/sync-inventory.yml) runs
   the sync every 2 hours and commits data + resized photos.

   To change the inventory: edit the Airtable. Never edit
   js/inventory.json or img/cars/ by hand — the sync overwrites
   them. See README for the family workflow.
   ============================================================ */

/* Formspree form ID for the financing lead form (see README).
   While empty, the form falls back to opening the visitor's
   email app addressed to valleauto@yahoo.com. */
const FORMSPREE_ID = "";      // ← paste Formspree form ID here

const COLOR_SWATCHES = {
  blanco: "#f5f5f2", negro: "#1c1c1e", gris: "#8e8e93", plata: "#c7c9cc",
  rojo: "#b3282d", azul: "#2b5aa7", verde: "#2e6b4f", marron: "#6b4a2f",
  dorado: "#c2a05a", amarillo: "#e8c839", anaranjado: "#d97a2b", vino: "#722f37"
};

/* Shown only if inventory.json is missing or empty. Kept empty on
   purpose — an empty lot message beats fake cars. */
const SAMPLE_CARS = [];

async function loadInventory() {
  try {
    const res = await fetch("js/inventory.json", { cache: "no-cache" });
    if (!res.ok) throw new Error("HTTP " + res.status);
    const data = await res.json();
    /* fill defaults so the rest of the site can assume every key exists */
    const cars = (Array.isArray(data.cars) ? data.cars : [])
      .filter(c => c && c.id && (c.make || c.title))
      .map(c => ({
        title: "", make: "", model: "", year: 0, color: "", mileage: 0,
        price: 0, body_type: "other", origin: "", registration_fee: "",
        condition_tags: [], photo_urls: [], featured: false, sold: false,
        notes: "", ...c
      }));
    return cars.length ? cars : SAMPLE_CARS;
  } catch (e) {
    console.warn("Could not load js/inventory.json, using sample data.", e);
    return SAMPLE_CARS;
  }
}
